name: eco_pilot
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # For state management (connecting UI to DashboardViewModel)
  provider: ^6.1.5+1

  # For Firebase connection
  firebase_core: ^3.2.0
  cloud_firestore: ^5.1.0
  firebase_auth: ^5.1.2 # We will need this for user IDs

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

